# Site settings
title: UAL Graphic Design Lecture Notes 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/notes"
url: "http://www.maxkoehler.com/" # the base hostname & protocol for your site
#url: "http://127.0.0.1:4000/notes" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
